### ISSUE TITLE
Sorry bother u again,  seems like i didnt have a checkpoint named "checkpoint_e34.pth"

### ISSUE THREAD

**Issue by EEEEEREN** [adrift00/Siamtracker#3]
i try to git clone your code and train it 
but i got some problem
![1](https://user-images.githubusercontent.com/67900018/112148132-77168380-8c18-11eb-89a4-fb79f3d217c7.png)

it saids i miss the file checkpointe34
but i found this things is not in your code on github
can you share it 🙏 🙏🙏🙏

or can i train this code without this thing ?

**Comment by adrift00** [comment]
It just a resume model, you can train it from epoch 0 and don't use it. Modify the config file like this:
![image](https://user-images.githubusercontent.com/35949066/112154251-0aeb4e00-8c1f-11eb-95d7-a0adf568ddf1.png)

**Comment by EEEEEREN** [comment]
i have finished training, so can i test these checkpoint on pysot ?
