### ISSUE TITLE
您好，您还有alexnet的预训练模型吗

### ISSUE THREAD

**Issue by EEEEEREN** [adrift00/Siamtracker#5]
不好意思打扰您，
我想试试您代码中的siamrpn部分，并且试试您已经在alexnet上尝试过的gradnet
但是我看到您 alexnet_config.yaml中没有    
PRETRAIN: False
PRETRAIN_PATH: '' " 
这两个接口，是否alexnet没有预训练模型呢

**Comment by adrift00** [comment]
您好，PRETRAIN接口决定是否使用pysot官方提供的模型，如果您需要，可以去pysot仓库下载。
